# JPX-Nikkei Index 400 Component Stocks
# Last updated: 2026-03-03 (As of February 27, 2026)
# Source: https://www.jpx.co.jp/english/markets/indices/jpx-nikkei400/
#         Official PDF: 400_e.pdf / 400_j.pdf
#
# Note: JPX-Nikkei 400 composition is reviewed annually (effective every August).
# The number of constituents may change due to delistings etc.
# Current count: 398 stocks

from __future__ import annotations

JPX400_TICKERS: list[dict[str, str]] = [
    {"ticker": "1332.T", "name": "ニッスイ", "name_en": "Nissui Corporation"},
    {"ticker": "1414.T", "name": "ショーボンドホールディングス", "name_en": "SHO-BOND Holdings Co.,Ltd."},
    {"ticker": "1419.T", "name": "タマホーム", "name_en": "Tama Home Co.,Ltd."},
    {"ticker": "1518.T", "name": "三井松島ホールディングス", "name_en": "MITSUI MATSUSHIMA HOLDINGS CO.,LTD."},
    {"ticker": "1605.T", "name": "ＩＮＰＥＸ", "name_en": "INPEX CORPORATION"},
    {"ticker": "1662.T", "name": "石油資源開発", "name_en": "Japan Petroleum Exploration Co.,Ltd."},
    {"ticker": "1719.T", "name": "安藤・間", "name_en": "HAZAMA ANDO CORPORATION"},
    {"ticker": "1721.T", "name": "コムシスホールディングス", "name_en": "COMSYS Holdings Corporation"},
    {"ticker": "1801.T", "name": "大成建設", "name_en": "TAISEI CORPORATION"},
    {"ticker": "1802.T", "name": "大林組", "name_en": "OBAYASHI CORPORATION"},
    {"ticker": "1808.T", "name": "長谷工コーポレーション", "name_en": "HASEKO Corporation"},
    {"ticker": "1812.T", "name": "鹿島建設", "name_en": "KAJIMA CORPORATION"},
    {"ticker": "1878.T", "name": "大東建託", "name_en": "DAITO TRUST CONSTRUCTION CO.,LTD."},
    {"ticker": "1911.T", "name": "住友林業", "name_en": "Sumitomo Forestry Co.,Ltd."},
    {"ticker": "1925.T", "name": "大和ハウス工業", "name_en": "DAIWA HOUSE INDUSTRY CO.,LTD."},
    {"ticker": "1928.T", "name": "積水ハウス", "name_en": "Sekisui House,Ltd."},
    {"ticker": "1942.T", "name": "関電工", "name_en": "KANDENKO CO.,LTD."},
    {"ticker": "1951.T", "name": "エクシオグループ", "name_en": "EXEO Group,Inc."},
    {"ticker": "1959.T", "name": "クラフティア", "name_en": "KRAFTIA CORPORATION"},
    {"ticker": "1969.T", "name": "高砂熱学工業", "name_en": "Takasago Thermal Engineering Co.,Ltd."},
    {"ticker": "2124.T", "name": "ジェイエイシーリクルートメント", "name_en": "JAC Recruitment Co.,Ltd."},
    {"ticker": "2127.T", "name": "日本Ｍ＆Ａセンターホールディングス", "name_en": "Nihon M&A Center Holdings Inc."},
    {"ticker": "2154.T", "name": "オープンアップグループ", "name_en": "Open Up Group Inc."},
    {"ticker": "2168.T", "name": "パソナグループ", "name_en": "Pasona Group Inc."},
    {"ticker": "2181.T", "name": "パーソルホールディングス", "name_en": "PERSOL HOLDINGS CO.,LTD."},
    {"ticker": "2201.T", "name": "森永製菓", "name_en": "Morinaga & Co.,Ltd."},
    {"ticker": "2222.T", "name": "寿スピリッツ", "name_en": "Kotobuki Spirits Co.,Ltd."},
    {"ticker": "2229.T", "name": "カルビー", "name_en": "CALBEE,Inc."},
    {"ticker": "2264.T", "name": "森永乳業", "name_en": "MORINAGA MILK INDUSTRY CO.,LTD."},
    {"ticker": "2267.T", "name": "ヤクルト本社", "name_en": "YAKULT HONSHA CO.,LTD."},
    {"ticker": "2269.T", "name": "明治ホールディングス", "name_en": "Meiji Holdings Co.,Ltd."},
    {"ticker": "2317.T", "name": "システナ", "name_en": "Systena Corporation"},
    {"ticker": "2327.T", "name": "日鉄ソリューションズ", "name_en": "NS Solutions Corporation"},
    {"ticker": "2371.T", "name": "カカクコム", "name_en": "Kakaku.com,Inc."},
    {"ticker": "2379.T", "name": "ディップ", "name_en": "dip Corporation"},
    {"ticker": "2384.T", "name": "ＳＢＳホールディングス", "name_en": "SBS Holdings,Inc."},
    {"ticker": "2413.T", "name": "エムスリー", "name_en": "M3,Inc."},
    {"ticker": "2502.T", "name": "アサヒグループホールディングス", "name_en": "Asahi Group Holdings,Ltd."},
    {"ticker": "2503.T", "name": "キリンホールディングス", "name_en": "Kirin Holdings Company,Limited"},
    {"ticker": "2531.T", "name": "宝ホールディングス", "name_en": "TAKARA HOLDINGS INC."},
    {"ticker": "2587.T", "name": "サントリー食品インターナショナル", "name_en": "Suntory Beverage & Food Limited"},
    {"ticker": "2670.T", "name": "エービーシー・マート", "name_en": "ABC-MART,INC."},
    {"ticker": "2678.T", "name": "アスクル", "name_en": "ASKUL Corporation"},
    {"ticker": "2685.T", "name": "アンドエスティＨＤ", "name_en": "and ST HD Co.,Ltd."},
    {"ticker": "2702.T", "name": "日本マクドナルドホールディングス", "name_en": "McDonald's Holdings Company(Japan),Ltd."},
    {"ticker": "2726.T", "name": "パルグループホールディングス", "name_en": "PAL GROUP Holdings CO.,LTD"},
    {"ticker": "2760.T", "name": "東京エレクトロン デバイス", "name_en": "TOKYO ELECTRON DEVICE LIMITED"},
    {"ticker": "2767.T", "name": "円谷フィールズホールディングス", "name_en": "TSUBURAYA FIELDS HOLDINGS INC."},
    {"ticker": "2768.T", "name": "双日", "name_en": "Sojitz Corporation"},
    {"ticker": "2801.T", "name": "キッコーマン", "name_en": "KIKKOMAN CORPORATION"},
    {"ticker": "2802.T", "name": "味の素", "name_en": "Ajinomoto Co.,Inc."},
    {"ticker": "2811.T", "name": "カゴメ", "name_en": "KAGOME CO.,LTD."},
    {"ticker": "2871.T", "name": "ニチレイ", "name_en": "NICHIREI CORPORATION"},
    {"ticker": "2875.T", "name": "東洋水産", "name_en": "TOYO SUISAN KAISHA,LTD."},
    {"ticker": "2897.T", "name": "日清食品ホールディングス", "name_en": "NISSIN FOODS HOLDINGS CO.,LTD."},
    {"ticker": "2914.T", "name": "日本たばこ産業", "name_en": "JAPAN TOBACCO INC."},
    {"ticker": "3003.T", "name": "ヒューリック", "name_en": "Hulic Co.,Ltd."},
    {"ticker": "3038.T", "name": "神戸物産", "name_en": "KOBE BUSSAN CO.,LTD."},
    {"ticker": "3064.T", "name": "ＭｏｎｏｔａＲＯ", "name_en": "MonotaRO Co.,Ltd."},
    {"ticker": "3086.T", "name": "Ｊ．フロント リテイリング", "name_en": "J.FRONT RETAILING Co.,Ltd."},
    {"ticker": "3088.T", "name": "マツキヨココカラ＆カンパニー", "name_en": "MatsukiyoCocokara & Co."},
    {"ticker": "3092.T", "name": "ＺＯＺＯ", "name_en": "ZOZO,Inc."},
    {"ticker": "3107.T", "name": "ダイワボウホールディングス", "name_en": "Daiwabo Holdings Co.,Ltd."},
    {"ticker": "3116.T", "name": "トヨタ紡織", "name_en": "TOYOTA BOSHOKU CORPORATION"},
    {"ticker": "3132.T", "name": "マクニカホールディングス", "name_en": "MACNICA HOLDINGS,INC."},
    {"ticker": "3148.T", "name": "クリエイトＳＤホールディングス", "name_en": "CREATE SD HOLDINGS CO.,LTD."},
    {"ticker": "3186.T", "name": "ネクステージ", "name_en": "NEXTAGE Co.,Ltd."},
    {"ticker": "3231.T", "name": "野村不動産ホールディングス", "name_en": "Nomura Real Estate Holdings,Inc."},
    {"ticker": "3288.T", "name": "オープンハウスグループ", "name_en": "Open House Group Co.,Ltd."},
    {"ticker": "3289.T", "name": "東急不動産ホールディングス", "name_en": "Tokyu Fudosan Holdings Corporation"},
    {"ticker": "3291.T", "name": "飯田グループホールディングス", "name_en": "Iida Group Holdings Co.,Ltd."},
    {"ticker": "3349.T", "name": "コスモス薬品", "name_en": "COSMOS Pharmaceutical Corporation"},
    {"ticker": "3360.T", "name": "シップヘルスケアホールディングス", "name_en": "SHIP HEALTHCARE HOLDINGS,INC."},
    {"ticker": "3382.T", "name": "セブン＆アイ・ホールディングス", "name_en": "Seven & i Holdings Co.,Ltd."},
    {"ticker": "3391.T", "name": "ツルハホールディングス", "name_en": "TSURUHA HOLDINGS INC."},
    {"ticker": "3402.T", "name": "東レ", "name_en": "TORAY INDUSTRIES,INC."},
    {"ticker": "3405.T", "name": "クラレ", "name_en": "KURARAY CO.,LTD."},
    {"ticker": "3436.T", "name": "ＳＵＭＣＯ", "name_en": "SUMCO CORPORATION"},
    {"ticker": "3465.T", "name": "ケイアイスター不動産", "name_en": "KI-STAR REAL ESTATE CO.,LTD"},
    {"ticker": "3549.T", "name": "クスリのアオキホールディングス", "name_en": "KUSURI NO AOKI HOLDINGS CO.,LTD."},
    {"ticker": "3563.T", "name": "ＦＯＯＤ ＆ ＬＩＦＥ ＣＯＭＰＡＮＩＥＳ", "name_en": "FOOD & LIFE COMPANIES LTD."},
    {"ticker": "3626.T", "name": "ＴＩＳ", "name_en": "TIS Inc."},
    {"ticker": "3635.T", "name": "コーエーテクモホールディングス", "name_en": "KOEI TECMO HOLDINGS CO.,LTD."},
    {"ticker": "3659.T", "name": "ネクソン", "name_en": "NEXON Co.,Ltd."},
    {"ticker": "3697.T", "name": "ＳＨＩＦＴ", "name_en": "SHIFT Inc."},
    {"ticker": "3765.T", "name": "ガンホー・オンライン・エンターテイメント", "name_en": "GungHo Online Entertainment,Inc."},
    {"ticker": "3769.T", "name": "ＧＭＯペイメントゲートウェイ", "name_en": "GMO Payment Gateway,Inc."},
    {"ticker": "3774.T", "name": "インターネットイニシアティブ", "name_en": "Internet Initiative Japan Inc."},
    {"ticker": "3861.T", "name": "王子ホールディングス", "name_en": "Oji Holdings Corporation"},
    {"ticker": "3923.T", "name": "ラクス", "name_en": "RAKUS Co.,Ltd."},
    {"ticker": "4004.T", "name": "レゾナック・ホールディングス", "name_en": "Resonac Holdings Corporation"},
    {"ticker": "4021.T", "name": "日産化学", "name_en": "Nissan Chemical Corporation"},
    {"ticker": "4042.T", "name": "東ソー", "name_en": "TOSOH CORPORATION"},
    {"ticker": "4062.T", "name": "イビデン", "name_en": "IBIDEN CO.,LTD."},
    {"ticker": "4063.T", "name": "信越化学工業", "name_en": "Shin-Etsu Chemical Co.,Ltd."},
    {"ticker": "4088.T", "name": "エア・ウォーター", "name_en": "AIR WATER INC."},
    {"ticker": "4091.T", "name": "日本酸素ホールディングス", "name_en": "NIPPON SANSO HOLDINGS CORPORATION"},
    {"ticker": "4151.T", "name": "協和キリン", "name_en": "Kyowa Kirin Co.,Ltd."},
    {"ticker": "4182.T", "name": "三菱瓦斯化学", "name_en": "Mitsubishi Gas Chemical Company,Inc."},
    {"ticker": "4183.T", "name": "三井化学", "name_en": "Mitsui Chemicals,Inc."},
    {"ticker": "4186.T", "name": "東京応化工業", "name_en": "TOKYO OHKA KOGYO CO.,LTD."},
    {"ticker": "4188.T", "name": "三菱ケミカルグループ", "name_en": "Mitsubishi Chemical Group Corporation"},
    {"ticker": "4194.T", "name": "ビジョナル", "name_en": "Visional,Inc."},
    {"ticker": "4202.T", "name": "ダイセル", "name_en": "Daicel Corporation"},
    {"ticker": "4203.T", "name": "住友ベークライト", "name_en": "Sumitomo Bakelite Company,Limited"},
    {"ticker": "4204.T", "name": "積水化学工業", "name_en": "Sekisui Chemical Co.,Ltd."},
    {"ticker": "4307.T", "name": "野村総合研究所", "name_en": "Nomura Research Institute,Ltd."},
    {"ticker": "4385.T", "name": "メルカリ", "name_en": "Mercari,Inc."},
    {"ticker": "4401.T", "name": "ＡＤＥＫＡ", "name_en": "ADEKA CORPORATION"},
    {"ticker": "4403.T", "name": "日油", "name_en": "NOF CORPORATION"},
    {"ticker": "4452.T", "name": "花王", "name_en": "Kao Corporation"},
    {"ticker": "4503.T", "name": "アステラス製薬", "name_en": "Astellas Pharma Inc."},
    {"ticker": "4507.T", "name": "塩野義製薬", "name_en": "Shionogi & Co.,Ltd."},
    {"ticker": "4516.T", "name": "日本新薬", "name_en": "Nippon Shinyaku Co.,Ltd."},
    {"ticker": "4519.T", "name": "中外製薬", "name_en": "CHUGAI PHARMACEUTICAL CO.,LTD."},
    {"ticker": "4523.T", "name": "エーザイ", "name_en": "Eisai Co.,Ltd."},
    {"ticker": "4527.T", "name": "ロート製薬", "name_en": "ROHTO PHARMACEUTICAL CO.,LTD."},
    {"ticker": "4528.T", "name": "小野薬品工業", "name_en": "ONO PHARMACEUTICAL CO.,LTD."},
    {"ticker": "4543.T", "name": "テルモ", "name_en": "TERUMO CORPORATION"},
    {"ticker": "4568.T", "name": "第一三共", "name_en": "DAIICHI SANKYO COMPANY,LIMITED"},
    {"ticker": "4578.T", "name": "大塚ホールディングス", "name_en": "Otsuka Holdings Co.,Ltd."},
    {"ticker": "4587.T", "name": "ペプチドリーム", "name_en": "PeptiDream Inc."},
    {"ticker": "4612.T", "name": "日本ペイントホールディングス", "name_en": "NIPPON PAINT HOLDINGS CO.,LTD."},
    {"ticker": "4613.T", "name": "関西ペイント", "name_en": "KANSAI PAINT CO.,LTD."},
    {"ticker": "4626.T", "name": "太陽ホールディングス", "name_en": "TAIYO HOLDINGS CO.,LTD."},
    {"ticker": "4661.T", "name": "オリエンタルランド", "name_en": "ORIENTAL LAND CO.,LTD."},
    {"ticker": "4666.T", "name": "パーク２４", "name_en": "PARK24 Co.,Ltd."},
    {"ticker": "4680.T", "name": "ラウンドワン", "name_en": "ROUND ONE Corporation"},
    {"ticker": "4681.T", "name": "リゾートトラスト", "name_en": "RESORTTRUST,INC."},
    {"ticker": "4684.T", "name": "オービック", "name_en": "OBIC Co.,Ltd."},
    {"ticker": "4686.T", "name": "ジャストシステム", "name_en": "JUSTSYSTEMS CORPORATION"},
    {"ticker": "4689.T", "name": "ＬＩＮＥヤフー", "name_en": "LY Corporation"},
    {"ticker": "4704.T", "name": "トレンドマイクロ", "name_en": "Trend Micro Incorporated"},
    {"ticker": "4716.T", "name": "日本オラクル", "name_en": "ORACLE CORPORATION JAPAN"},
    {"ticker": "4722.T", "name": "フューチャー", "name_en": "Future Corporation"},
    {"ticker": "4732.T", "name": "ユー・エス・エス", "name_en": "USS Co.,Ltd."},
    {"ticker": "4768.T", "name": "大塚商会", "name_en": "OTSUKA CORPORATION"},
    {"ticker": "4812.T", "name": "電通総研", "name_en": "DENTSU SOKEN INC."},
    {"ticker": "4816.T", "name": "東映アニメーション", "name_en": "TOEI ANIMATION CO.,LTD."},
    {"ticker": "4901.T", "name": "富士フイルムホールディングス", "name_en": "FUJIFILM Holdings Corporation"},
    {"ticker": "4912.T", "name": "ライオン", "name_en": "Lion Corporation"},
    {"ticker": "4967.T", "name": "小林製薬", "name_en": "KOBAYASHI PHARMACEUTICAL CO.,LTD."},
    {"ticker": "4980.T", "name": "デクセリアルズ", "name_en": "Dexerials Corporation"},
    {"ticker": "5019.T", "name": "出光興産", "name_en": "Idemitsu Kosan Co.,Ltd."},
    {"ticker": "5020.T", "name": "ＥＮＥＯＳホールディングス", "name_en": "ENEOS Holdings,Inc."},
    {"ticker": "5021.T", "name": "コスモエネルギーホールディングス", "name_en": "COSMO ENERGY HOLDINGS COMPANY,LIMITED"},
    {"ticker": "5032.T", "name": "ＡＮＹＣＯＬＯＲ", "name_en": "ANYCOLOR Inc."},
    {"ticker": "5076.T", "name": "インフロニア・ホールディングス", "name_en": "INFRONEER Holdings Inc."},
    {"ticker": "5101.T", "name": "横浜ゴム", "name_en": "The Yokohama Rubber Company,Limited"},
    {"ticker": "5105.T", "name": "ＴＯＹＯ ＴＩＲＥ", "name_en": "Toyo Tire Corporation"},
    {"ticker": "5108.T", "name": "ブリヂストン", "name_en": "BRIDGESTONE CORPORATION"},
    {"ticker": "5332.T", "name": "ＴＯＴＯ", "name_en": "TOTO LTD."},
    {"ticker": "5333.T", "name": "日本碍子", "name_en": "NGK INSULATORS,LTD."},
    {"ticker": "5334.T", "name": "日本特殊陶業", "name_en": "Niterra Co.,Ltd."},
    {"ticker": "5344.T", "name": "ＭＡＲＵＷＡ", "name_en": "MARUWA CO.,LTD."},
    {"ticker": "5393.T", "name": "ニチアス", "name_en": "NICHIAS CORPORATION"},
    {"ticker": "5401.T", "name": "日本製鉄", "name_en": "NIPPON STEEL CORPORATION"},
    {"ticker": "5406.T", "name": "神戸製鋼所", "name_en": "Kobe Steel,Ltd."},
    {"ticker": "5411.T", "name": "ＪＦＥホールディングス", "name_en": "JFE Holdings,Inc."},
    {"ticker": "5423.T", "name": "東京製鐵", "name_en": "TOKYO STEEL MANUFACTURING CO.,LTD."},
    {"ticker": "5444.T", "name": "大和工業", "name_en": "YAMATO KOGYO CO.,LTD."},
    {"ticker": "5471.T", "name": "大同特殊鋼", "name_en": "Daido Steel Co.,Ltd."},
    {"ticker": "5480.T", "name": "日本冶金工業", "name_en": "Nippon Yakin kogyo Co.,Ltd."},
    {"ticker": "5706.T", "name": "三井金属", "name_en": "Mitsui Kinzoku Company,Limited"},
    {"ticker": "5713.T", "name": "住友金属鉱山", "name_en": "Sumitomo Metal Mining Co.,Ltd."},
    {"ticker": "5714.T", "name": "ＤＯＷＡホールディングス", "name_en": "DOWA HOLDINGS CO.,LTD."},
    {"ticker": "5802.T", "name": "住友電気工業", "name_en": "Sumitomo Electric Industries,Ltd."},
    {"ticker": "5803.T", "name": "フジクラ", "name_en": "Fujikura Ltd."},
    {"ticker": "5805.T", "name": "ＳＷＣＣ", "name_en": "SWCC Corporation"},
    {"ticker": "5857.T", "name": "ＡＲＥホールディングス", "name_en": "ARE Holdings,Inc."},
    {"ticker": "5929.T", "name": "三和ホールディングス", "name_en": "Sanwa Holdings Corporation"},
    {"ticker": "5947.T", "name": "リンナイ", "name_en": "RINNAI CORPORATION"},
    {"ticker": "5991.T", "name": "日本発條", "name_en": "NHK SPRING CO.,LTD."},
    {"ticker": "6005.T", "name": "三浦工業", "name_en": "MIURA CO.,LTD."},
    {"ticker": "6098.T", "name": "リクルートホールディングス", "name_en": "Recruit Holdings Co.,Ltd."},
    {"ticker": "6101.T", "name": "ツガミ", "name_en": "TSUGAMI CORPORATION"},
    {"ticker": "6113.T", "name": "アマダ", "name_en": "AMADA CO.,LTD."},
    {"ticker": "6141.T", "name": "ＤＭＧ森精機", "name_en": "DMG MORI CO.,LTD."},
    {"ticker": "6146.T", "name": "ディスコ", "name_en": "DISCO CORPORATION"},
    {"ticker": "6201.T", "name": "豊田自動織機", "name_en": "TOYOTA INDUSTRIES CORPORATION"},
    {"ticker": "6254.T", "name": "野村マイクロ・サイエンス", "name_en": "Nomura Micro Science Co.,Ltd."},
    {"ticker": "6269.T", "name": "三井海洋開発", "name_en": "MODEC,INC."},
    {"ticker": "6273.T", "name": "ＳＭＣ", "name_en": "SMC CORPORATION"},
    {"ticker": "6301.T", "name": "小松製作所", "name_en": "KOMATSU LTD."},
    {"ticker": "6305.T", "name": "日立建機", "name_en": "Hitachi Construction Machinery Co.,Ltd."},
    {"ticker": "6323.T", "name": "ローツェ", "name_en": "RORZE CORPORATION"},
    {"ticker": "6326.T", "name": "クボタ", "name_en": "KUBOTA CORPORATION"},
    {"ticker": "6361.T", "name": "荏原製作所", "name_en": "EBARA CORPORATION"},
    {"ticker": "6367.T", "name": "ダイキン工業", "name_en": "DAIKIN INDUSTRIES,LTD."},
    {"ticker": "6368.T", "name": "オルガノ", "name_en": "ORGANO CORPORATION"},
    {"ticker": "6383.T", "name": "ダイフク", "name_en": "DAIFUKU CO.,LTD."},
    {"ticker": "6417.T", "name": "ＳＡＮＫＹＯ", "name_en": "SANKYO CO.,LTD."},
    {"ticker": "6432.T", "name": "竹内製作所", "name_en": "TAKEUCHI MFG.CO.,LTD."},
    {"ticker": "6436.T", "name": "アマノ", "name_en": "Amano Corporation"},
    {"ticker": "6448.T", "name": "ブラザー工業", "name_en": "BROTHER INDUSTRIES,LTD."},
    {"ticker": "6460.T", "name": "セガサミーホールディングス", "name_en": "SEGA SAMMY HOLDINGS INC."},
    {"ticker": "6465.T", "name": "ホシザキ", "name_en": "HOSHIZAKI CORPORATION"},
    {"ticker": "6479.T", "name": "ミネベアミツミ", "name_en": "MINEBEA MITSUMI Inc."},
    {"ticker": "6501.T", "name": "日立製作所", "name_en": "Hitachi,Ltd."},
    {"ticker": "6503.T", "name": "三菱電機", "name_en": "Mitsubishi Electric Corporation"},
    {"ticker": "6504.T", "name": "富士電機", "name_en": "FUJI ELECTRIC CO.,LTD."},
    {"ticker": "6506.T", "name": "安川電機", "name_en": "YASKAWA Electric Corporation"},
    {"ticker": "6532.T", "name": "ベイカレント", "name_en": "BayCurrent,Inc."},
    {"ticker": "6544.T", "name": "ジャパンエレベーターサービスホールディングス", "name_en": "JAPAN ELEVATOR SERVICE HOLDINGS CO.,LTD."},
    {"ticker": "6586.T", "name": "マキタ", "name_en": "Makita Corporation"},
    {"ticker": "6590.T", "name": "芝浦メカトロニクス", "name_en": "SHIBAURA MECHATRONICS CORPORATION"},
    {"ticker": "6632.T", "name": "ＪＶＣケンウッド", "name_en": "JVCKENWOOD Corporation"},
    {"ticker": "6645.T", "name": "オムロン", "name_en": "OMRON Corporation"},
    {"ticker": "6670.T", "name": "ＭＣＪ", "name_en": "MCJ Co.,Ltd."},
    {"ticker": "6701.T", "name": "日本電気", "name_en": "NEC Corporation"},
    {"ticker": "6702.T", "name": "富士通", "name_en": "Fujitsu Limited"},
    {"ticker": "6707.T", "name": "サンケン電気", "name_en": "Sanken Electric Co.,Ltd."},
    {"ticker": "6723.T", "name": "ルネサスエレクトロニクス", "name_en": "Renesas Electronics Corporation"},
    {"ticker": "6724.T", "name": "セイコーエプソン", "name_en": "SEIKO EPSON CORPORATION"},
    {"ticker": "6728.T", "name": "アルバック", "name_en": "ULVAC, Inc."},
    {"ticker": "6752.T", "name": "パナソニック ホールディングス", "name_en": "Panasonic Holdings Corporation"},
    {"ticker": "6758.T", "name": "ソニーグループ", "name_en": "SONY GROUP CORPORATION"},
    {"ticker": "6762.T", "name": "ＴＤＫ", "name_en": "TDK Corporation"},
    {"ticker": "6787.T", "name": "メイコー", "name_en": "Meiko Electronics Co.,Ltd."},
    {"ticker": "6806.T", "name": "ヒロセ電機", "name_en": "HIROSE ELECTRIC CO.,LTD."},
    {"ticker": "6841.T", "name": "横河電機", "name_en": "YOKOGAWA ELECTRIC CORPORATION"},
    {"ticker": "6845.T", "name": "アズビル", "name_en": "Azbil Corporation"},
    {"ticker": "6849.T", "name": "日本光電工業", "name_en": "NIHON KOHDEN CORPORATION"},
    {"ticker": "6856.T", "name": "堀場製作所", "name_en": "HORIBA,Ltd."},
    {"ticker": "6857.T", "name": "アドバンテスト", "name_en": "ADVANTEST CORPORATION"},
    {"ticker": "6861.T", "name": "キーエンス", "name_en": "KEYENCE CORPORATION"},
    {"ticker": "6869.T", "name": "シスメックス", "name_en": "SYSMEX CORPORATION"},
    {"ticker": "6902.T", "name": "デンソー", "name_en": "DENSO CORPORATION"},
    {"ticker": "6920.T", "name": "レーザーテック", "name_en": "Lasertec Corporation"},
    {"ticker": "6951.T", "name": "日本電子", "name_en": "JEOL Ltd."},
    {"ticker": "6954.T", "name": "ファナック", "name_en": "FANUC CORPORATION"},
    {"ticker": "6965.T", "name": "浜松ホトニクス", "name_en": "HAMAMATSU PHOTONICS K.K."},
    {"ticker": "6966.T", "name": "三井ハイテック", "name_en": "Mitsui High-tec,Inc."},
    {"ticker": "6981.T", "name": "村田製作所", "name_en": "Murata Manufacturing Co.,Ltd."},
    {"ticker": "6988.T", "name": "日東電工", "name_en": "NITTO DENKO CORPORATION"},
    {"ticker": "7003.T", "name": "三井Ｅ＆Ｓ", "name_en": "MITSUI E&S Co.,Ltd."},
    {"ticker": "7004.T", "name": "カナデビア", "name_en": "Kanadevia Corporation"},
    {"ticker": "7011.T", "name": "三菱重工業", "name_en": "Mitsubishi Heavy Industries,Ltd."},
    {"ticker": "7012.T", "name": "川崎重工業", "name_en": "Kawasaki Heavy Industries,Ltd."},
    {"ticker": "7013.T", "name": "ＩＨＩ", "name_en": "IHI Corporation"},
    {"ticker": "7014.T", "name": "名村造船所", "name_en": "Namura Shipbuilding Co.,Ltd."},
    {"ticker": "7105.T", "name": "三菱ロジスネクスト", "name_en": "Mitsubishi Logisnext Co.,Ltd."},
    {"ticker": "7148.T", "name": "ＦＰＧ", "name_en": "Financial Partners Group Co.,Ltd."},
    {"ticker": "7164.T", "name": "全国保証", "name_en": "ZENKOKU HOSHO Co.,Ltd."},
    {"ticker": "7167.T", "name": "めぶきフィナンシャルグループ", "name_en": "Mebuki Financial Group,Inc."},
    {"ticker": "7186.T", "name": "横浜フィナンシャルグループ", "name_en": "Yokohama Financial Group,Inc."},
    {"ticker": "7202.T", "name": "いすゞ自動車", "name_en": "ISUZU MOTORS LIMITED"},
    {"ticker": "7203.T", "name": "トヨタ自動車", "name_en": "TOYOTA MOTOR CORPORATION"},
    {"ticker": "7211.T", "name": "三菱自動車工業", "name_en": "MITSUBISHI MOTORS CORPORATION"},
    {"ticker": "7259.T", "name": "アイシン", "name_en": "AISIN CORPORATION"},
    {"ticker": "7261.T", "name": "マツダ", "name_en": "Mazda Motor Corporation"},
    {"ticker": "7267.T", "name": "本田技研工業", "name_en": "HONDA MOTOR CO.,LTD."},
    {"ticker": "7269.T", "name": "スズキ", "name_en": "SUZUKI MOTOR CORPORATION"},
    {"ticker": "7270.T", "name": "ＳＵＢＡＲＵ", "name_en": "SUBARU CORPORATION"},
    {"ticker": "7272.T", "name": "ヤマハ発動機", "name_en": "Yamaha Motor Co.,Ltd."},
    {"ticker": "7276.T", "name": "小糸製作所", "name_en": "KOITO MANUFACTURING CO.,LTD."},
    {"ticker": "7282.T", "name": "豊田合成", "name_en": "TOYODA GOSEI CO.,LTD."},
    {"ticker": "7309.T", "name": "シマノ", "name_en": "SHIMANO INC."},
    {"ticker": "7419.T", "name": "ノジマ", "name_en": "Nojima Co.,Ltd."},
    {"ticker": "7453.T", "name": "良品計画", "name_en": "RYOHIN KEIKAKU CO.,LTD."},
    {"ticker": "7459.T", "name": "メディパルホールディングス", "name_en": "MEDIPAL HOLDINGS CORPORATION"},
    {"ticker": "7532.T", "name": "パン・パシフィック・インターナショナルホールディングス", "name_en": "Pan Pacific International Holdings Corporation"},
    {"ticker": "7550.T", "name": "ゼンショーホールディングス", "name_en": "ZENSHO HOLDINGS CO.,LTD."},
    {"ticker": "7564.T", "name": "ワークマン", "name_en": "WORKMAN CO.,LTD."},
    {"ticker": "7599.T", "name": "ＩＤＯＭ", "name_en": "IDOM Inc."},
    {"ticker": "7649.T", "name": "スギホールディングス", "name_en": "SUGI HOLDINGS Co.,LTD."},
    {"ticker": "7701.T", "name": "島津製作所", "name_en": "Shimadzu Corporation"},
    {"ticker": "7716.T", "name": "ナカニシ", "name_en": "NAKANISHI INC."},
    {"ticker": "7729.T", "name": "東京精密", "name_en": "TOKYO SEIMITSU CO.,LTD."},
    {"ticker": "7733.T", "name": "オリンパス", "name_en": "OLYMPUS CORPORATION"},
    {"ticker": "7735.T", "name": "ＳＣＲＥＥＮホールディングス", "name_en": "SCREEN Holdings Co.,Ltd."},
    {"ticker": "7740.T", "name": "タムロン", "name_en": "Tamron Co.,Ltd."},
    {"ticker": "7741.T", "name": "ＨＯＹＡ", "name_en": "HOYA CORPORATION"},
    {"ticker": "7744.T", "name": "ノーリツ鋼機", "name_en": "Noritsu Koki Co.,Ltd."},
    {"ticker": "7747.T", "name": "朝日インテック", "name_en": "ASAHI INTECC CO.,LTD."},
    {"ticker": "7751.T", "name": "キヤノン", "name_en": "CANON INC."},
    {"ticker": "7762.T", "name": "シチズン時計", "name_en": "Citizen Watch Co.,Ltd."},
    {"ticker": "7832.T", "name": "バンダイナムコホールディングス", "name_en": "Bandai Namco Holdings Inc."},
    {"ticker": "7846.T", "name": "パイロットコーポレーション", "name_en": "PILOT CORPORATION"},
    {"ticker": "7867.T", "name": "タカラトミー", "name_en": "TOMY COMPANY,LTD."},
    {"ticker": "7906.T", "name": "ヨネックス", "name_en": "YONEX CO.,LTD."},
    {"ticker": "7912.T", "name": "大日本印刷", "name_en": "Dai Nippon Printing Co.,Ltd."},
    {"ticker": "7936.T", "name": "アシックス", "name_en": "ASICS Corporation"},
    {"ticker": "7944.T", "name": "ローランド", "name_en": "Roland Corporation"},
    {"ticker": "7951.T", "name": "ヤマハ", "name_en": "YAMAHA CORPORATION"},
    {"ticker": "7974.T", "name": "任天堂", "name_en": "Nintendo Co.,Ltd."},
    {"ticker": "7988.T", "name": "ニフコ", "name_en": "NIFCO INC."},
    {"ticker": "7994.T", "name": "オカムラ", "name_en": "OKAMURA CORPORATION"},
    {"ticker": "8001.T", "name": "伊藤忠商事", "name_en": "ITOCHU Corporation"},
    {"ticker": "8002.T", "name": "丸紅", "name_en": "Marubeni Corporation"},
    {"ticker": "8015.T", "name": "豊田通商", "name_en": "TOYOTA TSUSHO CORPORATION"},
    {"ticker": "8020.T", "name": "兼松", "name_en": "KANEMATSU CORPORATION"},
    {"ticker": "8031.T", "name": "三井物産", "name_en": "MITSUI & CO.,LTD."},
    {"ticker": "8035.T", "name": "東京エレクトロン", "name_en": "Tokyo Electron Limited"},
    {"ticker": "8053.T", "name": "住友商事", "name_en": "SUMITOMO CORPORATION"},
    {"ticker": "8056.T", "name": "ＢＩＰＲＯＧＹ", "name_en": "BIPROGY Inc."},
    {"ticker": "8058.T", "name": "三菱商事", "name_en": "Mitsubishi Corporation"},
    {"ticker": "8060.T", "name": "キヤノンマーケティングジャパン", "name_en": "Canon Marketing Japan Inc."},
    {"ticker": "8078.T", "name": "阪和興業", "name_en": "HANWA CO.,LTD."},
    {"ticker": "8088.T", "name": "岩谷産業", "name_en": "IWATANI CORPORATION"},
    {"ticker": "8098.T", "name": "稲畑産業", "name_en": "Inabata & Co.,Ltd."},
    {"ticker": "8111.T", "name": "ゴールドウイン", "name_en": "Goldwin Inc."},
    {"ticker": "8113.T", "name": "ユニ・チャーム", "name_en": "UNICHARM CORPORATION"},
    {"ticker": "8130.T", "name": "サンゲツ", "name_en": "Sangetsu Corporation"},
    {"ticker": "8133.T", "name": "伊藤忠エネクス", "name_en": "ITOCHU ENEX CO.,LTD."},
    {"ticker": "8136.T", "name": "サンリオ", "name_en": "Sanrio Company,Ltd."},
    {"ticker": "8154.T", "name": "加賀電子", "name_en": "KAGA ELECTRONICS CO.,LTD."},
    {"ticker": "8174.T", "name": "日本瓦斯", "name_en": "NIPPON GAS CO.,LTD."},
    {"ticker": "8194.T", "name": "ライフコーポレーション", "name_en": "LIFE CORPORATION"},
    {"ticker": "8227.T", "name": "しまむら", "name_en": "SHIMAMURA Co.,Ltd."},
    {"ticker": "8252.T", "name": "丸井グループ", "name_en": "MARUI GROUP CO.,LTD."},
    {"ticker": "8253.T", "name": "クレディセゾン", "name_en": "Credit Saison Co.,Ltd."},
    {"ticker": "8306.T", "name": "三菱ＵＦＪフィナンシャル・グループ", "name_en": "Mitsubishi UFJ Financial Group,Inc."},
    {"ticker": "8308.T", "name": "りそなホールディングス", "name_en": "Resona Holdings, Inc."},
    {"ticker": "8309.T", "name": "三井住友トラストグループ", "name_en": "Sumitomo Mitsui Trust Group,Inc."},
    {"ticker": "8316.T", "name": "三井住友フィナンシャルグループ", "name_en": "Sumitomo Mitsui Financial Group,Inc."},
    {"ticker": "8331.T", "name": "千葉銀行", "name_en": "The Chiba Bank,Ltd."},
    {"ticker": "8354.T", "name": "ふくおかフィナンシャルグループ", "name_en": "Fukuoka Financial Group,Inc."},
    {"ticker": "8410.T", "name": "セブン銀行", "name_en": "Seven Bank,Ltd."},
    {"ticker": "8411.T", "name": "みずほフィナンシャルグループ", "name_en": "Mizuho Financial Group,Inc."},
    {"ticker": "8424.T", "name": "芙蓉総合リース", "name_en": "Fuyo General Lease Co.,Ltd."},
    {"ticker": "8425.T", "name": "みずほリース", "name_en": "Mizuho Leasing Company,Limited"},
    {"ticker": "8439.T", "name": "東京センチュリー", "name_en": "Tokyo Century Corporation"},
    {"ticker": "8473.T", "name": "ＳＢＩホールディングス", "name_en": "SBI Holdings,Inc."},
    {"ticker": "8515.T", "name": "アイフル", "name_en": "AIFUL CORPORATION"},
    {"ticker": "8572.T", "name": "アコム", "name_en": "ACOM CO.,LTD."},
    {"ticker": "8584.T", "name": "ジャックス", "name_en": "JACCS CO.,LTD."},
    {"ticker": "8591.T", "name": "オリックス", "name_en": "ORIX CORPORATION"},
    {"ticker": "8593.T", "name": "三菱ＨＣキャピタル", "name_en": "Mitsubishi HC Capital Inc."},
    {"ticker": "8601.T", "name": "大和証券グループ本社", "name_en": "Daiwa Securities Group Inc."},
    {"ticker": "8604.T", "name": "野村ホールディングス", "name_en": "Nomura Holdings, Inc."},
    {"ticker": "8630.T", "name": "ＳＯＭＰＯホールディングス", "name_en": "Sompo Holdings,Inc."},
    {"ticker": "8697.T", "name": "日本取引所グループ", "name_en": "Japan Exchange Group,Inc."},
    {"ticker": "8725.T", "name": "ＭＳ＆ＡＤインシュアランスグループホールディングス", "name_en": "MS&AD Insurance Group Holdings,Inc."},
    {"ticker": "8729.T", "name": "ソニーフィナンシャルグループ", "name_en": "Sony Financial Group Inc."},
    {"ticker": "8750.T", "name": "第一生命ホールディングス", "name_en": "Dai-ichi Life Holdings,Inc."},
    {"ticker": "8766.T", "name": "東京海上ホールディングス", "name_en": "Tokio Marine Holdings,Inc."},
    {"ticker": "8801.T", "name": "三井不動産", "name_en": "Mitsui Fudosan Co.,Ltd."},
    {"ticker": "8802.T", "name": "三菱地所", "name_en": "Mitsubishi Estate Company,Limited"},
    {"ticker": "8804.T", "name": "東京建物", "name_en": "Tokyo Tatemono Co.,Ltd."},
    {"ticker": "8830.T", "name": "住友不動産", "name_en": "Sumitomo Realty & Development Co.,Ltd."},
    {"ticker": "8848.T", "name": "レオパレス２１", "name_en": "LEOPALACE21 CORPORATION"},
    {"ticker": "8850.T", "name": "スターツコーポレーション", "name_en": "STARTS CORPORATION INC."},
    {"ticker": "8876.T", "name": "リログループ", "name_en": "Relo Group,Inc."},
    {"ticker": "8919.T", "name": "カチタス", "name_en": "KATITAS CO.,LTD"},
    {"ticker": "8923.T", "name": "トーセイ", "name_en": "TOSEI CORPORATION"},
    {"ticker": "9005.T", "name": "東急", "name_en": "TOKYU CORPORATION"},
    {"ticker": "9006.T", "name": "京浜急行電鉄", "name_en": "Keikyu Corporation"},
    {"ticker": "9007.T", "name": "小田急電鉄", "name_en": "Odakyu Electric Railway Co.,Ltd."},
    {"ticker": "9008.T", "name": "京王電鉄", "name_en": "Keio Corporation"},
    {"ticker": "9009.T", "name": "京成電鉄", "name_en": "Keisei Electric Railway Co.,Ltd."},
    {"ticker": "9021.T", "name": "西日本旅客鉄道", "name_en": "West Japan Railway Company"},
    {"ticker": "9022.T", "name": "東海旅客鉄道", "name_en": "Central Japan Railway Company"},
    {"ticker": "9024.T", "name": "西武ホールディングス", "name_en": "SEIBU HOLDINGS INC."},
    {"ticker": "9041.T", "name": "近鉄グループホールディングス", "name_en": "Kintetsu Group Holdings Co.,Ltd."},
    {"ticker": "9064.T", "name": "ヤマトホールディングス", "name_en": "YAMATO HOLDINGS CO.,LTD."},
    {"ticker": "9065.T", "name": "山九", "name_en": "SANKYU INC."},
    {"ticker": "9069.T", "name": "センコーグループホールディングス", "name_en": "SENKO Group Holdings Co.,Ltd."},
    {"ticker": "9090.T", "name": "ＡＺ－ＣＯＭ丸和ホールディングス", "name_en": "AZ-COM MARUWA Holdings Inc."},
    {"ticker": "9101.T", "name": "日本郵船", "name_en": "Nippon Yusen Kabushiki Kaisha"},
    {"ticker": "9104.T", "name": "商船三井", "name_en": "Mitsui O.S.K.Lines,Ltd."},
    {"ticker": "9107.T", "name": "川崎汽船", "name_en": "Kawasaki Kisen Kaisha,Ltd."},
    {"ticker": "9110.T", "name": "ＮＳユナイテッド海運", "name_en": "NS United Kaiun Kaisha,Ltd."},
    {"ticker": "9119.T", "name": "飯野海運", "name_en": "IINO KAIUN KAISHA,LTD."},
    {"ticker": "9142.T", "name": "九州旅客鉄道", "name_en": "Kyushu Railway Company"},
    {"ticker": "9143.T", "name": "ＳＧホールディングス", "name_en": "SG HOLDINGS CO.,LTD."},
    {"ticker": "9147.T", "name": "ＮＩＰＰＯＮ ＥＸＰＲＥＳＳホールディングス", "name_en": "NIPPON EXPRESS HOLDINGS,INC."},
    {"ticker": "9201.T", "name": "日本航空", "name_en": "Japan Airlines Co.,Ltd."},
    {"ticker": "9202.T", "name": "ＡＮＡホールディングス", "name_en": "ANA HOLDINGS INC."},
    {"ticker": "9302.T", "name": "三井倉庫ホールディングス", "name_en": "MITSUI-SOKO HOLDINGS Co.,Ltd."},
    {"ticker": "9418.T", "name": "Ｕ－ＮＥＸＴ ＨＯＬＤＩＮＧＳ", "name_en": "U-NEXT HOLDINGS Co.,Ltd."},
    {"ticker": "9432.T", "name": "ＮＴＴ", "name_en": "NTT,Inc."},
    {"ticker": "9433.T", "name": "ＫＤＤＩ", "name_en": "KDDI CORPORATION"},
    {"ticker": "9434.T", "name": "ソフトバンク", "name_en": "SoftBank Corp."},
    {"ticker": "9435.T", "name": "光通信", "name_en": "HIKARI TSUSHIN,INC."},
    {"ticker": "9449.T", "name": "ＧＭＯインターネットグループ", "name_en": "GMO internet group,Inc."},
    {"ticker": "9502.T", "name": "中部電力", "name_en": "Chubu Electric Power Company,Incorporated"},
    {"ticker": "9503.T", "name": "関西電力", "name_en": "The Kansai Electric Power Company,Incorporated"},
    {"ticker": "9506.T", "name": "東北電力", "name_en": "Tohoku Electric Power Company,Incorporated"},
    {"ticker": "9507.T", "name": "四国電力", "name_en": "Shikoku Electric Power Company,Incorporated"},
    {"ticker": "9508.T", "name": "九州電力", "name_en": "Kyushu Electric Power Company,Incorporated"},
    {"ticker": "9509.T", "name": "北海道電力", "name_en": "Hokkaido Electric Power Company,Incorporated"},
    {"ticker": "9513.T", "name": "電源開発", "name_en": "Electric Power Development Co.,Ltd."},
    {"ticker": "9531.T", "name": "東京瓦斯", "name_en": "TOKYO GAS CO.,LTD."},
    {"ticker": "9532.T", "name": "大阪瓦斯", "name_en": "OSAKA GAS CO.,LTD."},
    {"ticker": "9602.T", "name": "東宝", "name_en": "TOHO CO.,LTD"},
    {"ticker": "9684.T", "name": "スクウェア・エニックス・ホールディングス", "name_en": "SQUARE ENIX HOLDINGS CO.,LTD."},
    {"ticker": "9697.T", "name": "カプコン", "name_en": "CAPCOM CO.,LTD."},
    {"ticker": "9735.T", "name": "セコム", "name_en": "SECOM CO.,LTD."},
    {"ticker": "9744.T", "name": "メイテックグループホールディングス", "name_en": "MEITEC Group Holdings Inc."},
    {"ticker": "9759.T", "name": "ＮＳＤ", "name_en": "NSD CO.,LTD."},
    {"ticker": "9766.T", "name": "コナミグループ", "name_en": "KONAMI GROUP CORPORATION"},
    {"ticker": "9843.T", "name": "ニトリホールディングス", "name_en": "Nitori Holdings Co.,Ltd."},
    {"ticker": "9962.T", "name": "ミスミグループ本社", "name_en": "MISUMI Group Inc."},
    {"ticker": "9983.T", "name": "ファーストリテイリング", "name_en": "FAST RETAILING CO.,LTD."},
    {"ticker": "9984.T", "name": "ソフトバンクグループ", "name_en": "SoftBank Group Corp."},
    {"ticker": "9989.T", "name": "サンドラッグ", "name_en": "SUNDRUG CO.,LTD."},
    {"ticker": "417A.T", "name": "ブルーゾーンホールディングス", "name_en": "BLUE ZONES HOLDINGS CO.,LTD."},
]


def get_jpx400_tickers() -> list[str]:
    """Return a list of JPX-Nikkei 400 ticker symbols (e.g. ['1332.T', '1414.T', ...])."""
    return [item["ticker"] for item in JPX400_TICKERS]


def get_jpx400_names() -> dict[str, str]:
    """Return a dict mapping ticker -> Japanese company name."""
    return {item["ticker"]: item["name"] for item in JPX400_TICKERS}


def get_jpx400_names_en() -> dict[str, str]:
    """Return a dict mapping ticker -> English company name."""
    return {item["ticker"]: item["name_en"] for item in JPX400_TICKERS}
